name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  

  build:

    runs-on: ubuntu-latest

    environment: 
      name: StringGeneratorEnv

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.10.3'

    - name: Pre-build
      run: sudo chmod +x ./build.sh

    - name: Build and Publish NuGet
      run: ./build.sh Push --NugetApiKey ${{ secrets.NUGET_API_KEY }}
