name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    steps:
    - uses: actions/checkout@v2
    - name: Setup netcoreapp3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: netcoreapp3.1
        
    - name: Pre-build
      run: sudo chmod +x ./build.sh

    - name: Build
      run: ./build.sh
