name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  environment: 
      name: StringGeneratorEnv

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Pre-build
      run: sudo chmod +x ./build.sh

    - name: Build and Publish NuGet
      run: ./build.sh Push --NugetApiKey ${{ secrets.NUGET_API_KEY }}
